install.packages("dplyr")
library("dplyr")
data(iris)
summary(iris)
iris %>% top_n(3, Sepal.Width)
filter <- filter (iris, Species == "setosa")
head(filter,3)
select <- select (iris, Sepal.Length, Sepal.Width, Petal.Length)
head(select)
select <- select (iris, -Sepal.Length, -Sepal.Width)
head(select)
select(iris, starts_with("S"))
select(iris,ends_with("S"))
select (iris, -c (Petal.Width, Sepal.Width,Sepal.Length))
arrange(iris, Sepal.Length)
arrange(iris, Sepal.Length, Sepal.Width)
arrange (iris,  desc(Sepal.Width))
iris %>% arrange (Sepal.Width)
col1 <- mutate(iris, Greater.Half = Sepal.Width > 0.5 * Sepal.Length)
head(col1)
mutate(iris, New_col = Sepal.Length * 2)
summarise(iris, meanSL=mean(Sepal.Length),
          meanSW=mean(Sepal.Width),
          meanPL=mean(Petal.Length),
          meanPW=mean(Petal.Width))
iris %>% summarise(C=n())
iris %>% 
  group_by(Species)
iris %>% count(Sepal.Width>=3.1)
slice(iris , 140:150)
rename(iris, SL=Sepal.Length , SW=Sepal.Width)
